/**
 * Error Codes Constants
 * Centralized location for all application error codes
 */

const ERROR_CODES = {
  // HTTP Status Related Errors
  BAD_REQUEST: "BAD_REQUEST",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  NOT_FOUND: "NOT_FOUND",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  CONFLICT: "CONFLICT",
  UNPROCESSABLE_ENTITY: "UNPROCESSABLE_ENTITY",
  TOO_MANY_REQUESTS: "TOO_MANY_REQUESTS",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  SERVICE_UNAVAILABLE: "SERVICE_UNAVAILABLE",
  INVALID_ID: "INVALID_ID",

  // Authentication & Authorization Errors
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_MISSING: "TOKEN_MISSING",
  INVALID_TOKEN: "INVALID_TOKEN",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  ACCESS_DENIED: "ACCESS_DENIED",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  ACCOUNT_LOCKED: "ACCOUNT_LOCKED",
  ACCOUNT_SUSPENDED: "ACCOUNT_SUSPENDED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",

  // User Management Errors
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_ALREADY_EXISTS: "USER_ALREADY_EXISTS",
  EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
  USERNAME_ALREADY_EXISTS: "USERNAME_ALREADY_EXISTS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
  INVALID_USER_ID: "INVALID_USER_ID",
  USER_CREATION_FAILED: "USER_CREATION_FAILED",
  USER_UPDATE_FAILED: "USER_UPDATE_FAILED",
  USER_DELETION_FAILED: "USER_DELETION_FAILED",

  // Validation Errors
  CUSTOM_VALIDATION_ERROR: "CUSTOM_VALIDATION_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  REQUIRED_FIELD_MISSING: "REQUIRED_FIELD_MISSING",
  INVALID_EMAIL_FORMAT: "INVALID_EMAIL_FORMAT",
  INVALID_PHONE_FORMAT: "INVALID_PHONE_FORMAT",
  INVALID_PASSWORD_FORMAT: "INVALID_PASSWORD_FORMAT",
  PASSWORD_TOO_WEAK: "PASSWORD_TOO_WEAK",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",
  INVALID_DATE_FORMAT: "INVALID_DATE_FORMAT",
  INVALID_URL_FORMAT: "INVALID_URL_FORMAT",
  INVALID_JSON_FORMAT: "INVALID_JSON_FORMAT",
  FIELD_TOO_SHORT: "FIELD_TOO_SHORT",
  FIELD_TOO_LONG: "FIELD_TOO_LONG",
  INVALID_ENUM_VALUE: "INVALID_ENUM_VALUE",
  INVALID_DATA_TYPE: "INVALID_DATA_TYPE",

  // Database Errors
  DATABASE_CONNECTION_ERROR: "DATABASE_CONNECTION_ERROR",
  DATABASE_QUERY_ERROR: "DATABASE_QUERY_ERROR",
  DATABASE_TIMEOUT: "DATABASE_TIMEOUT",
  DUPLICATE_ENTRY: "DUPLICATE_ENTRY",
  FOREIGN_KEY_CONSTRAINT: "FOREIGN_KEY_CONSTRAINT",
  DATA_INTEGRITY_ERROR: "DATA_INTEGRITY_ERROR",
  TRANSACTION_FAILED: "TRANSACTION_FAILED",
  MIGRATION_ERROR: "MIGRATION_ERROR",

  // File Upload Errors
  FILE_UPLOAD_ERROR: "FILE_UPLOAD_ERROR",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  INVALID_FILE_TYPE: "INVALID_FILE_TYPE",
  FILE_UPLOAD_FAILED: "FILE_UPLOAD_FAILED",
  FILE_DELETION_FAILED: "FILE_DELETION_FAILED",
  INVALID_FILE_FORMAT: "INVALID_FILE_FORMAT",
  FILE_CORRUPTED: "FILE_CORRUPTED",
  STORAGE_QUOTA_EXCEEDED: "STORAGE_QUOTA_EXCEEDED",
  UNSUPPORTED_FILE_EXTENSION: "UNSUPPORTED_FILE_EXTENSION",
  FILE_REQUIRED: "FILE_REQUIRED",

  // Content Management Errors
  CONTENT_NOT_FOUND: "CONTENT_NOT_FOUND",
  CONTENT_ALREADY_EXISTS: "CONTENT_ALREADY_EXISTS",
  CONTENT_CREATION_FAILED: "CONTENT_CREATION_FAILED",
  CONTENT_UPDATE_FAILED: "CONTENT_UPDATE_FAILED",
  CONTENT_DELETION_FAILED: "CONTENT_DELETION_FAILED",
  CONTENT_ALREADY_PUBLISHED: "CONTENT_ALREADY_PUBLISHED",
  CONTENT_NOT_PUBLISHED: "CONTENT_NOT_PUBLISHED",
  CONTENT_LOCKED: "CONTENT_LOCKED",

  // Rate Limiting Errors
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  TOO_MANY_LOGIN_ATTEMPTS: "TOO_MANY_LOGIN_ATTEMPTS",
  TOO_MANY_PASSWORD_RESET_ATTEMPTS: "TOO_MANY_PASSWORD_RESET_ATTEMPTS",
  TOO_MANY_EMAIL_VERIFICATION_ATTEMPTS: "TOO_MANY_EMAIL_VERIFICATION_ATTEMPTS",
  API_QUOTA_EXCEEDED: "API_QUOTA_EXCEEDED",
  REQUEST_FREQUENCY_TOO_HIGH: "REQUEST_FREQUENCY_TOO_HIGH",

  // Payment & Billing Errors
  PAYMENT_FAILED: "PAYMENT_FAILED",
  PAYMENT_DECLINED: "PAYMENT_DECLINED",
  INSUFFICIENT_FUNDS: "INSUFFICIENT_FUNDS",
  INVALID_PAYMENT_METHOD: "INVALID_PAYMENT_METHOD",
  PAYMENT_METHOD_EXPIRED: "PAYMENT_METHOD_EXPIRED",
  SUBSCRIPTION_NOT_FOUND: "SUBSCRIPTION_NOT_FOUND",
  SUBSCRIPTION_EXPIRED: "SUBSCRIPTION_EXPIRED",
  SUBSCRIPTION_CANCELLED: "SUBSCRIPTION_CANCELLED",
  BILLING_ADDRESS_INVALID: "BILLING_ADDRESS_INVALID",

  // External API Errors
  EXTERNAL_API_ERROR: "EXTERNAL_API_ERROR",
  EXTERNAL_API_TIMEOUT: "EXTERNAL_API_TIMEOUT",
  EXTERNAL_API_RATE_LIMITED: "EXTERNAL_API_RATE_LIMITED",
  EXTERNAL_SERVICE_UNAVAILABLE: "EXTERNAL_SERVICE_UNAVAILABLE",
  INVALID_API_KEY: "INVALID_API_KEY",
  API_KEY_EXPIRED: "API_KEY_EXPIRED",
  THIRD_PARTY_AUTHENTICATION_FAILED: "THIRD_PARTY_AUTHENTICATION_FAILED",

  // Email & Communication Errors
  EMAIL_SEND_FAILED: "EMAIL_SEND_FAILED",
  EMAIL_TEMPLATE_NOT_FOUND: "EMAIL_TEMPLATE_NOT_FOUND",
  INVALID_EMAIL_TEMPLATE: "INVALID_EMAIL_TEMPLATE",
  SMS_SEND_FAILED: "SMS_SEND_FAILED",
  NOTIFICATION_SEND_FAILED: "NOTIFICATION_SEND_FAILED",
  COMMUNICATION_SERVICE_ERROR: "COMMUNICATION_SERVICE_ERROR",

  // Cache Errors
  CACHE_ERROR: "CACHE_ERROR",
  CACHE_KEY_NOT_FOUND: "CACHE_KEY_NOT_FOUND",
  CACHE_SET_FAILED: "CACHE_SET_FAILED",
  CACHE_DELETE_FAILED: "CACHE_DELETE_FAILED",
  CACHE_CONNECTION_ERROR: "CACHE_CONNECTION_ERROR",

  // Search & Query Errors
  SEARCH_ERROR: "SEARCH_ERROR",
  INVALID_SEARCH_QUERY: "INVALID_SEARCH_QUERY",
  SEARCH_INDEX_ERROR: "SEARCH_INDEX_ERROR",
  SEARCH_SERVICE_UNAVAILABLE: "SEARCH_SERVICE_UNAVAILABLE",
  NO_SEARCH_RESULTS: "NO_SEARCH_RESULTS",

  // Configuration & Environment Errors
  MISSING_CONFIGURATION: "MISSING_CONFIGURATION",
  INVALID_CONFIGURATION: "INVALID_CONFIGURATION",
  ENVIRONMENT_VARIABLE_MISSING: "ENVIRONMENT_VARIABLE_MISSING",
  FEATURE_DISABLED: "FEATURE_DISABLED",
  MAINTENANCE_MODE: "MAINTENANCE_MODE",

  // Security Errors
  SECURITY_VIOLATION: "SECURITY_VIOLATION",
  SUSPICIOUS_ACTIVITY: "SUSPICIOUS_ACTIVITY",
  IP_BLOCKED: "IP_BLOCKED",
  CSRF_TOKEN_INVALID: "CSRF_TOKEN_INVALID",
  CAPTCHA_VERIFICATION_FAILED: "CAPTCHA_VERIFICATION_FAILED",
  ENCRYPTION_ERROR: "ENCRYPTION_ERROR",
  DECRYPTION_ERROR: "DECRYPTION_ERROR",

  // Business Logic Errors
  BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
  OPERATION_NOT_ALLOWED: "OPERATION_NOT_ALLOWED",
  RESOURCE_LOCKED: "RESOURCE_LOCKED",
  DEADLINE_EXCEEDED: "DEADLINE_EXCEEDED",
  QUOTA_EXCEEDED: "QUOTA_EXCEEDED",
  DEPENDENCY_ERROR: "DEPENDENCY_ERROR",

  // Session & State Errors
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_INVALID: "SESSION_INVALID",
  STATE_MISMATCH: "STATE_MISMATCH",
  INVALID_REQUEST_STATE: "INVALID_REQUEST_STATE",
  CONCURRENT_MODIFICATION: "CONCURRENT_MODIFICATION",

  // Network & Connectivity Errors
  NETWORK_ERROR: "NETWORK_ERROR",
  CONNECTION_TIMEOUT: "CONNECTION_TIMEOUT",
  DNS_RESOLUTION_FAILED: "DNS_RESOLUTION_FAILED",
  SSL_CERTIFICATE_ERROR: "SSL_CERTIFICATE_ERROR",
  PROXY_ERROR: "PROXY_ERROR",

  // Resource Management Errors
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  RESOURCE_ALREADY_EXISTS: "RESOURCE_ALREADY_EXISTS",
  RESOURCE_CREATION_FAILED: "RESOURCE_CREATION_FAILED",
  RESOURCE_UPDATE_FAILED: "RESOURCE_UPDATE_FAILED",
  RESOURCE_DELETION_FAILED: "RESOURCE_DELETION_FAILED",
  RESOURCE_LIMIT_EXCEEDED: "RESOURCE_LIMIT_EXCEEDED",

  // Backup & Recovery Errors
  BACKUP_FAILED: "BACKUP_FAILED",
  RESTORE_FAILED: "RESTORE_FAILED",
  BACKUP_NOT_FOUND: "BACKUP_NOT_FOUND",
  BACKUP_CORRUPTED: "BACKUP_CORRUPTED",
  RECOVERY_IN_PROGRESS: "RECOVERY_IN_PROGRESS",
};

module.exports = ERROR_CODES;
